#!/usr/bin/env bash
#install nginx on server and configure it to show hello world!

apt-get update
apt-get install -y nginx
ufw allow 'Nginx HTTP'

echo "Hello World!" > /var/www/html/index.html
sudo service nginx start
