#!/usr/bin/env bash
#install nginx on server and configure it to show hello world!
apt-get -y update
apt-get -y install nginx
ufw allow 'Nginx HTTP'
echo "Hello World!" > /var/www/html/index.html
sudo service nginx start
