#!/usr/bin/env bash
#configure Nginx server so that /redirect_me is redirecting to another page
sudo apt-get -y update
sudo apt-get -y install nginx
echo "Hello World!" > /var/www/html/index.html
echo "Ceci n'est pas une page" > /var/www/html/err_404.html
sed -i "s/server_name _;/server_name _;\n\trewrite ^\/redirect_me https:\/\/www.youtube.com\/watch?v=QH2-TGUlwu4 permanent;\n\n\terror_page 404 \/err_404.html;\n\tlocation = \/err_404.html {\n\t\troot \/usr\/var\/www\/html;\n\t\tinternal;\n\t}/" /etc/nginx/sites-available/default
service nginx restart
