#!/usr/bin/env bash
# return the value of a custom header which get the hostname of the server.

sudo apt-get -y update
sudo apt-get -y install nginx
sudo ufw allow 'Nginx HTTP'

echo "Hello World!" > /var/www/html/index.html
sed -i "s/server_name _;/server_name _;\n\trewrite ^\/redirect_me https:\/\/www.youtube.com\/watch?v=QH2-TGUlwu4 permanent;/" /etc/nginx/sites-available/default
echo "Ceci n'est pas une page" > /usr/share/nginx/html/err_404.html
sudo sed -i "s/server_name _;/server_name _;\n\trewrite ^\/redirect_me https:\/\/www.youtube.com\/watch?v=QH2-TGUlwu4 permanent;\n\n\terror_page 404 \/err_404.html;\n\tlocation = \/err_404.html {\n\t\troot \/usr\/share\/nginx\/html;\n\t\tinternal;\n\t}/" /etc/nginx/sites-available/default
Server_Name=$(hostname)
echo -e "\n# Add custom header\nadd_header X-Served-By $Server_Name;" | sudo tee -a /etc/nginx/sites-available/default > /dev/null

sudo service nginx restart
