#!/usr/bin/env bash
#Install and configure HAproxy on your lb-01 server.

sudo apt-get -y update
sudo apt-get -y install software-properties-common
sudo apt-get -y install haproxy
echo "frontend web-front
	bind *:80
	default_backend web-backend

backend web-backend
	balance roundrobin
	server web-01 54.237.41.246 check
	server web-02 18.207.1.177 check" | sudo tee -a /etc/haproxy/haproxy.cfg
sudo service haproxy start
