#!/usr/bin/env bash
#debug nginx server to listen to port 80 and start the service
sudo apt-get -y update
sudo apt-get install -y curl
sudo apt-get install -y nginx
rm /etc/nginx/sites-enabled/*~
sed -i 's/8080/80/g' /etc/nginx/sites-enabled/default
ln -sf /etc/nginx/sites-available/default /etc/nginx/sites-enabled/
sudo service nginx restart
