#!/usr/bin/env bash
#bash shows a mssg and echo another when it is terminated
term_sig()
{
	echo "I am invincible!!!"
}
trap 'term_sig' SIGTERM

while true; do
	echo "To infinity and beyond"
	sleep 2
done
